all:
	latex bouquin.tex
	latex bouquin.tex
	dvips bouquin.dvi
	ps2pdf bouquin.ps

clean:
	rm -rf **/*.aux
	rm -rf **/*.pdf
	rm -rf **/*.dvi
	rm -rf **/*.ps
	rm -rf **/*.idx
	rm -rf **/*.ilg
	rm -rf **/*.ind
	rm -rf **/*.log
	rm -rf **/*.toc
